from __future__ import annotations

from typing import Protocol

from easy_quant.domain.identity.entities import Invitation, User, UserSession


class IdentityRepository(Protocol):
    def has_any_user(self) -> bool: ...

    def add_user(self, user: User) -> None: ...

    def get_user(self, user_id: str) -> User | None: ...

    def get_user_by_username(self, username: str) -> User | None: ...

    def add_invitation(self, invitation: Invitation) -> None: ...

    def get_invitation_by_hash(self, token_hash: str) -> Invitation | None: ...

    def add_session(self, session: UserSession) -> None: ...

    def get_session_by_hash(self, token_hash: str) -> UserSession | None: ...

    def save_session(self, session: UserSession) -> None: ...

    def list_users(self) -> tuple[User, ...]: ...

    def save_user(self, user: User) -> None: ...

    def list_invitations(self) -> tuple[Invitation, ...]: ...
