const labels: Record<string, string> = {
  active: "运行中",
  pending: "待处理",
  paused: "已暂停",
  terminated: "已终止",
  succeeded: "已成功",
  failed: "失败",
  retry: "等待重试",
  delivered: "已送达",
  confirmed: "已确认",
  rejected: "已拒绝",
  corrected: "已修正",
  timed_out: "运行超时",
  cancelled: "已取消",
  queued: "已排队",
  disabled: "已停用",
  admin: "管理员",
  user: "普通用户",
  buy: "买入",
  sell: "卖出",
  hold: "持有",
  email: "邮件",
  ntfy: "ntfy 推送",
  "market-data-acquisition": "每日行情更新",
  "live-analysis": "实盘策略分析",
  before_market: "盘前",
  on_market: "盘中",
  after_market: "盘后",
  create: "创建",
  update: "更新",
  execute: "执行",
  import: "导入",
  schedule: "定时任务",
  invitation: "邀请码",
  "data-source-config": "数据来源配置",
  "data-acquisition": "数据获取任务",
  dataset: "数据集",
}

export const localizedLabel = (value: string) => labels[value] ?? value
